start_message = "Type <ansiblue>@help</ansiblue> to see the command list"

[local]
task_file_local = "~/.local/della/tasks.toml"

[remote]
use_remote = false

[style]
[[style.tasks_display]]
fg = "cyan"

[[style.tasks_display]]
fg = "green"

[[style.tasks_display]]
fg = "white"

[style.normal]
fg = "white"

[style.alert]
fg = "red"
extra = "bold"

[style.highlight_command]
fg = "blue"
extra = "italic"

[style.highlight_date]
fg = "white"
bg = "blue"
extra = "italic"

[style.highlight_task]
fg = "yellow"
extra = "bold"

[style.choose_title]
fg = "blue"

[style.choose_selected]
fg = "green"
extra = "italic underline"

[style.choose_unselected]
fg = "cyan"
